# Generated by Django 4.0.3 on 2022-03-08 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='anwswer',
            new_name='answer',
        ),
    ]
