# Generated by Django 4.0.3 on 2022-03-11 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sqa', '0003_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sqa.tenant'),
            preserve_default=False,
        ),
    ]
