# Generated by Django 4.0.3 on 2022-03-13 17:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sqa', '0006_answer_upsert_at_answer_upsert_by_category_upsert_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='upsert_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 13, 23, 1, 32, 323), null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='upsert_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 13, 23, 1, 31, 999323), null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='upsert_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 13, 23, 1, 32, 323), null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='upsert_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 13, 23, 1, 31, 999323), null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
